// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://belpblzvapcmmpdgjshy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbHBibHp2YXBjbW1wZGdqc2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mjg5NTEsImV4cCI6MjA2MTAwNDk1MX0.xQGNYlLXTq1IXlioS0L_OVFvN3nP31iJTBqPOScIq34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);